name: Build and distribute package
on:
  push:
  pull_request:

jobs:

  build:
    name: Build and check package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package
      run: |
        pip install poetry
        poetry install
        poetry build
    - name: Validates package metadata
      run: |
        poetry check
        poetry run twine check ./dist/*

  release:
    name: Create a release on GitHub
    runs-on: ubuntu-latest
    needs: build
    # Only triggers on version tagging.
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./dist/*

  pypi:
    name: Push package to public PyPi repository
    runs-on: ubuntu-latest
    needs: release
    steps:
    - uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{secrets.PYPI_TOKEN}}

  version-bump:
    name: Test post-release version bump
    runs-on: ubuntu-latest
    # needs: release
    steps:
    - name: Bump patch revision
      run: |
        poetry run bumpversion --verbose patch
