name: Pull-requests labeller (based on file changes)
on:
- pull_request

jobs:
  labeller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: ".github/pr_labeler.yaml"
