name: Generate and sync labels
on:
  # Only the develop branch has authority on the project management. This will
  # prevent any other tagging or release activity interfer with the project.
  push:
    branches:
      - develop

jobs:

  labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mpm
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
    - name: Generate labels
      run: |
        poetry run generate_labels
    - name: Discard all local changes but the label definitions file
      run: |
        # Remove untracked directories and files.
        git clean -fd
        # Temporarily stash our target file.
        git stash -- ./.github/labels.json
        # Reset all repository.
        git checkout --force
        # Restore modified file.
        git stash pop
    - name: Create PR
      uses: peter-evans/create-pull-request@v2
      with:
        commit-message: "[github] Update project labels."
        title: '[github] Update project labels.'
        body: |
          Update project's labels.

          Auto-generated by [GitHub action](https://github.com/kdeldycke/meta-package-manager/blob/develop/.github/workflows/labels.yaml).
        labels: "manager: mpm"
        assignees: kdeldycke
        reviewers: kdeldycke
        branch: labels-update
    - name: Sync labels
      uses: lannonbr/issue-label-manager-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
