name: Code linting
on:
  push:
    # QA on master is too late: we shouldn't mess with the code at this point.
    branches-ignore:
      - 'master'
  pull_request:

jobs:

  sort-python-imports:
    name: Auto-sort Python imports and auto-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Required by git-auto-commit-action. See:
        # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Sort imports
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
        poetry run isort --apply
    - name: Commit and push changes
      # Only allow autocommits on develop branch and pull requests.
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_author: "Kevin Deldycke <kevin@deldycke.com>"
        commit_message: "[lint] Sort python module imports."
        file_pattern: "*.py"

  lint-python:
    name: Lint and check Python code
    # No need to lint before the auto formatting did its job.
    needs: sort-python-imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
        poetry run pycodestyle
        poetry run pylint meta_package_manager

  lint-json:
    name: Lint JSON files and create a PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install JSON Lint
      run: |
        sudo npm install jsonlint -g
    - name: Lint
      run: |
        find ./ -type f -name '*.json' -print -exec jsonlint --in-place "{}" \;
    - name: Create PR
      uses: peter-evans/create-pull-request@v2
      with:
        author: "Kevin Deldycke <kevin@deldycke.com>"
        commit-message: "[lint] Auto-format JSON content."
        title: '[lint] Auto-format JSON content.'
        body: |
          Auto-generated by [GitHub action](https://github.com/kdeldycke/meta-package-manager/blob/develop/.github/workflows/lint.yaml).
        labels: "CI/CD"
        assignees: kdeldycke
        branch: lint-json

  fix-typo:
    name: Auto-fix typos and create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@0.1.0
      - uses: peter-evans/create-pull-request@v2
        with:
          author: "Kevin Deldycke <kevin@deldycke.com>"
          commit-message: "[lint] Fix typo."
          title: "Typo."
          body: |
            Generated by [GitHub action](https://github.com/kdeldycke/meta-package-manager/blob/master/.github/workflows/lint.yaml).
          labels: "documentation"
          assignees: kdeldycke
          branch: fix-typo

  update-gitignore:
    name: Generate .gitignore and create a PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git-extras package
        run: |
          sudo apt install -y git-extras
      - name: Generate .gitignore
        run: |
          git ignore-io --replace emacs git linux macos nohup python vim virtualenv visualstudiocode windows
          echo 'poetry.lock' >> ./.gitignore
      - uses: peter-evans/create-pull-request@v2
        with:
          author: "Kevin Deldycke <kevin@deldycke.com>"
          commit-message: "Regenerate .gitignore."
          title: "Regenerate .gitignore"
          body: |
            Generated by [GitHub action](https://github.com/kdeldycke/meta-package-manager/blob/master/.github/workflows/lint.yaml).
          labels: "CI/CD"
          assignees: kdeldycke
          branch: update-gitignore
