name: Code linting
on:
  push:
    # QA on master is too late: we shouldn't mess with the code at this point.
    branches-ignore:
      - 'master'
  pull_request:

jobs:

  sort-python-imports:
    name: Auto-sort Python imports and auto-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Required by git-auto-commit-action. See:
        # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Sort imports
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
        poetry run isort --apply
    - name: Commit and push changes
      # Only allow autocommits on develop branch and pull requests.
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_author: "Kevin Deldycke <kevin@deldycke.com>"
        commit_message: "[lint] Sort python module imports."
        file_pattern: "*.py"

  lint-python:
    name: Lint and check Python code
    # No need to lint before the auto formatting did its job.
    needs: sort-python-imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
        poetry run pycodestyle
        poetry run pylint meta_package_manager

  fix_typo:
    name: Typo auto-fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sobolevn/misspell-fixer-action@0.1.0
      - uses: peter-evans/create-pull-request@v2
        with:
          author: "Kevin Deldycke <kevin@deldycke.com>"
          commit-message: "[lint] Fix typo."
          title: "Typo."
          labels: "documentation"
          assignees: "kdeldycke"
          body: |
            Generated by [GitHub action](https://github.com/kdeldycke/meta-package-manager/blob/master/.github/workflows/lint.yaml).
