name: Code linting
on:
  push:
    branches:
      - '**'  # matches all branches.
      # QA on master is too late: we shouldn't mess with the code at this
      # point.
      - '!master'
  pull_request:

jobs:

  auto-format:
    name: Automaticcaly format and clean up code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Required by git-auto-commit-action. See:
        # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
        ref: ${{github.head_ref}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Sort imports
      run: |
        pip install poetry
        poetry install
        poetry run isort --apply
    - name: Commit and push changes
      # Only allow autocommits on develop branch and pull requests.
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: "GitHub Actions"
        commit_user_email: "action@github.com"
        commit_message: "[lint] Sort python module imports."
        file_pattern: "*.py"

  lint:
    name: Lint and check code
    # No need to lint before the auto formatting did its job.
    needs: auto-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        pip install poetry
        poetry install
        poetry run pycodestyle
        poetry run pylint meta_package_manager
