name: Unittests
on: [push, pull_request]

jobs:

  unittests:
    name: Unit-tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    - name: Upgrade Homebrew
      if: runner.os == 'macOS'
      run: |
        brew update
    - name: Install npm
      run: |
        npm install -g npm
    - name: Install gem
      run: |
        gem update --system
    - name: Install Atom on macOS
      if: runner.os == 'macOS'
      run: |
        brew install Caskroom/cask/atom
    - name: Install Atom on Linux
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -y ppa:webupd8team/atom
        sudo apt update
        sudo apt install -y atom
    - name: Install mas on macOS
      if: runner.os == 'macOS'
      run: |
        brew install mas
    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip
    - name: Install mpm and its dependencies
      run: |
        pip install -e .[tests]
    - name: mpm CLI output for debugging
      run: |
        mpm managers
    - name: Launch unittests in destructive mode
      env:
        DESTRUCTIVE_TESTS: true
      run: |
        pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        pip install -e .[tests]
        pycodestyle

  packaging:
    name: Packaging tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Check building package works
      run: |
        pip install -e .[develop]
        ./setup.py sdist bdist_egg bdist_wheel
    - name: Validates package metadata
      run: |
        ./setup.py check -m -r -s
