name: Unittests
on:
  push:
  pull_request:
  create:
  schedule:
    # Run tests every week to catch regressions from external dependencies.
    - cron: 17 9 * * 1

jobs:

  tests:
    name: Tests
    # No need to get furher if code style doesn't check.
    needs: lint
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # See what each os came pre-installed with at:
        # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.7, 3.8]
        # Python 2.7 tests only targets BitBar plugins on macOS.
        exclude:
          - os: ubuntu-latest
            python-version: 2.7
          - os: windows-latest
            python-version: 2.7
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Linux - Fix runner cache folder permissions
      if: runner.os == 'Linux'
      run: |
        mkdir -p /home/runner/.cache
        sudo chown -R runner /home/runner/.cache

    ### Install or upgrade package managers on each platform, and made them
    ### ready to use for mpm.

    # Homebrew
    - name: macOS - Upgrade Homebrew
      if: runner.os == 'macOS'
      run: |
        brew update

    # Apt
    - name: Linux - Upgrade apt
      if: runner.os == 'Linux'
      run: |
        sudo apt update

    # Chocolatey
    - name: Windows - Upgrade Chocolatey
      if: runner.os == 'Windows'
      run: |
        choco upgrade chocolatey

    # NPM
    - name: Linux - Install npm
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y node-gyp nodejs-dev libssl1.0-dev npm
    - name: macOS - Install npm
      if: runner.os == 'macOS'
      run: |
        brew unlink node@12
        brew install npm
    - name: Windows - Upgrade npm
      if: runner.os == 'Windows'
      run: |
        npm install -g npm

    # Yarn
    - name: macOS - Install Yarn
      if: runner.os == 'macOS'
      run: |
        brew install yarn
    - name: Linux - Install Yarn
      if: runner.os == 'Linux'
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt update
        sudo apt install -y yarn
    - name: Windows - Install Yarn
      if: runner.os == 'Windows'
      run: |
        choco install yarn

    # Composer
    - name: macOS - Install Composer
      if: runner.os == 'macOS'
      run: |
        brew install composer
    - name: Windows - Install Composer
      if: runner.os == 'Windows'
      run: |
        choco install composer

    # APM
    - name: macOS - Install Atom
      if: runner.os == 'macOS'
      run: |
        brew install Caskroom/cask/atom
    - name: Linux - Install Atom
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -y ppa:webupd8team/atom
        sudo apt install -y atom
    - name: Windows - Install Atom
      if: runner.os == 'Windows'
      run: |
        choco install atom

    # MAS
    - name: macOS - Install mas
      if: runner.os == 'macOS'
      run: |
        brew install mas

    # Flatpak
    - name: Linux - Install Flatpak
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -y ppa:alexlarsson/flatpak
        sudo apt install -y flatpak

    # Snap
    - name: Linux - Upgrade Snapd
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y snapd

    # Gem
    - name: macOS & Windows - Upgrade gem
      if: runner.os != 'Linux'
      run: |
        gem update --system
    - name: Linux - Upgrade gem
      if: runner.os == 'Linux'
      run: |
        sudo gem update --system

    # Pip
    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    # Mpm
    - name: Install mpm and its dependencies
      run: |
        pip install poetry
        poetry install
    - name: mpm CLI output for debugging
      run: |
        poetry run mpm managers
    - name: Hack trying to fix coverage - "Can't combine line data with arc data" error
      if: runner.os != 'Windows'
      run: |
        rm -rf .coverage*
    - name: Test BitBar plugin
      if: matrix.python-version == '2.7'
      run: |
        # mpm 2.8 is the last supporting Python 2.7.
        python -m pip install "meta-package-manager~=2.8"
        python -m unittest discover -p test_bitbar_plugin.py
    - name: Tests and coverage report in destructive mode
      if: matrix.python-version != '2.7'
      env:
        DESTRUCTIVE_TESTS: true
      # pyproject.toml config file is specified at CLI level instead of letting
      # coverage find it because of this bug:
      # https://github.com/nedbat/coveragepy/issues/512#issuecomment-399707938
      # https://github.com/pytest-dev/pytest-cov/issues/168#issuecomment-327533847
      # https://github.com/pytest-dev/pytest-cov/issues/243
      run: |
        poetry run pytest --cov-config=pyproject.toml --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  auto-format:
    name: Automaticcaly format and clean up code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Required by git-auto-commit-action. See:
        # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
        ref: ${{github.head_ref}}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Sort imports
      run: |
        pip install poetry
        poetry install
        poetry run isort --apply
    - name: Commit and push changes only on develop branch
      if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.event.ref == 'develop')
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: "GitHub Actions"
        commit_user_email: "action@github.com"
        commit_message: "[lint] Sort python module imports."
        file_pattern: "*.py"

  lint:
    name: Lint and check code
    # No need to lint before the auto formatting did its job.
    needs: auto-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        pip install poetry
        poetry install
        poetry run pycodestyle
        poetry run pylint meta_package_manager

  build:
    name: Build, check and deploy package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build package
      run: |
        pip install poetry
        poetry install
        poetry build
    - name: Validates package metadata
      run: |
        poetry check
        poetry run twine check ./dist/*
    - name: Push package to public PyPi repository
      # Only triggers on tagging.
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{secrets.pypi_token}}
    - name: Test post release version bump
      run: |
        poetry run bumpversion --verbose patch
