name: Unittests
on: [push, pull_request]

jobs:

  unittests:
    name: Unit-tests
    strategy:
      matrix:
        # See what each os came pre-installed with at:
        # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
    # Upgrade default packagers on each platform.
    - name: macOS - Upgrade Homebrew
      if: runner.os == 'macOS'
      run: |
        brew update
    - name: Linux - Upgrade apt
      if: runner.os == 'Linux'
      run: |
        sudo apt update
    - name: Windows - Upgrade Chocolatey
      if: runner.os == 'Windows'
      run: |
        choco upgrade chocolatey
    # Install missing package managers on all platforms.
    - name: Linux - Install npm
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y npm
    - name: macOS - Install PHP Composer
      if: runner.os == 'macOS'
      run: |
        brew install composer
    - name: Windows - Install PHP Composer
      if: runner.os == 'Windows'
      run: |
        choco install composer
    - name: macOS - Install Atom
      if: runner.os == 'macOS'
      run: |
        brew install Caskroom/cask/atom
    - name: Linux - Install Atom
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -y ppa:webupd8team/atom
        sudo apt install -y atom
    - name: Windows - Install Atom
      if: runner.os == 'Windows'
      run: |
        choco install atom
    - name: macOS - Install mas
      if: runner.os == 'macOS'
      run: |
        brew install mas
    # Upgrade all additional package managers.
    - name: Upgrade npm
      run: |
        npm install -g npm
    - name: Upgrade gem
      run: |
        gem update --system
    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip
    # mpm steps.
    - name: Install mpm and its dependencies
      run: |
        pip install -e .[tests]
    - name: mpm CLI output for debugging
      run: |
        mpm managers
    - name: Launch unittests in destructive mode
      env:
        DESTRUCTIVE_TESTS: true
      run: |
        pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Check coding style
      run: |
        pip install -e .[tests]
        pycodestyle

  packaging:
    name: Packaging tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Check building package works
      run: |
        pip install -e .[develop]
        ./setup.py sdist bdist_egg bdist_wheel
    - name: Validates package metadata
      run: |
        ./setup.py check -m -r -s
